### ISSUE TITLE
<foreign> and <ref> to be made active in <div type="commentary">

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#72]
Please make sure (1) that `<foreign>` in `<div type="commentary">` has the same effect as elsewhere, i.e. to create italics in display, and (2) that `<ref>` creates a hyperlink.

For example, current display of this code:

`<div type="commentary">
            <p n="1v4-1v5">Stutterheim (<bibl rend="omitname"><ptr target="bib:Stutterheim1935_01"/></bibl>) observed that the words <foreign>tamān paṅujara muvaḥ</foreign> (which he still quoted in Brandes' reading with <foreign>tatān</foreign>) find a parallel in the word <foreign>tan punaruktā</foreign> at the end of the <ref target="Palebuhan.xml">Palebuhan inscription</ref>. The correspondence of this closing paragraph with the final words preserved of the <ref target="Laguna.xml">Laguna plate</ref> are even more remarkable.</p>
         </div>`

is like this:

<img width="1017" alt="Capture d’écran 2020-09-23 à 18 06 14" src="https://user-images.githubusercontent.com/835603/94039047-829f0400-fdc7-11ea-8347-2bdee2dce689.png">

**Comment by ajaniak** [comment]
I have implemented as much as I could the link for <ref> pointing towards the github pages. However, since all the files aren't stored in one system, I can't retrieved all the information necessary to provide all the links, so for now the links only work for files in the same folder. We could fake it a little more, but it implies reorganizing all the repositories according to the same folders path.  Indeed, XSLT can transformed data but can compiled it as a programming language could do. 

We could create a collection of path for each files;, but honestly, it is not worth the work in my opinion since once we have a XML database identifying the storage location won't be an issue anymore.

So for the example you have provided above: the link for Palebuhan works, but for Lagunas you will have a 404 error (By the way, I couldn't find this file so I have tested with others files where I have a location) I have let the debugging messages so you could understand the working while transforming.

**Comment by arlogriffiths** [comment]
Thanks. 

Indeed, I didn't expect anymore than display as hyperlink, regardless of whether the link would work or not. (I knew it would not for Laguna.xml, because I haven't created that file yet.) The present display is certainly satisfactory for now.

But for your information, if I click in the untracked `file:///Users/arlogriffiths/Documents/GitHub/DHARMA/project-documentation/stylesheets/output/Guntur2020-10-03.html` on my computer on the hyperlink for Palehuban, I get the same error screen as when I click on the hyperlink for Laguna:

<img width="1677" alt="Capture d’écran 2020-10-03 à 09 13 08" src="https://user-images.githubusercontent.com/835603/94985657-b95be380-0558-11eb-895e-8ad57742efc2.png">

If that is the behavior you were expecting, then you can close this issue after reading this message.

**Comment by ajaniak** [comment]
It is strange you don't have the Palehuban link working... It does on my side. 
Since you just expect a working link, I think it would be best to only point toward the main page of the repository github rather than directing toward 404 error pages. Would it be ok for you?

**Comment by arlogriffiths** [comment]
I still get that page 404 if I click on Palebuhan in my html for Guntur — this is not at all an important issue, to I am not reopening this issue, but just send you this message for information
